baseURL = 'https://abhi010bh.github.io/PortfoBlog/'
languageCode = 'en-us'
author='Abhishek Haibatti'
paginate=3

# ------------------------------
theme = "paper"
title = "Literary Cradle"

[params]
  color = 'linen'


 
  name = 'Abhishek Haibatti'
  bio = 'Discover fresh context'
# ------------------------------
# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

  [[menu.main]]
    identifier = "Portfolio Home"
    name= "Portfolio Home"
    url="https://abhi010bh.github.io/"
    weight=10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true